### ISSUE TITLE
Vite Assets config + lightningcss?

### ISSUE THREAD

**Issue by addy** [odoe/arcgis-map-comps-react-simple#1]
Hey there,

We have our own wrapper for React around the ArcGIS JS API. There aren't really any decent examples out there (across GitHub at least) for Vite lib-mode projects wrapping the ArcGIS SDK, specifically around pulling in the ArcGIS assets. I'm super curious to know how you guys envisioned it being bundled/built. You wouldn't happen to have a good example config for reference, would you?

**Comment by odoe** [comment]
I haven't see anything using library mode. I would think you would want `@arcgis/core` external though, and let users load it, but I'm not sure. If you need to bundle it with your library, it would still be pretty big because of the dynamic imports, even though runtime loads would be minimal. I don't know of any good examples this out there.
